version: '3'

services:
    dependencies:
        build:
            context: .
            dockerfile: Dockerfile
        image: "sfneal/dependencies:${TAG}"
        env_file: .env.docker
        container_name: dependencies
        tty: true
        volumes:
            - dependencies:/var/www
        depends_on:
            - dependencies-cache
        networks:
            - dependencies-network

    dependencies-cache:
        container_name: dependencies-cache
        image: redis:6-alpine
        command: ["redis-server", "--appendonly yes", "--port 9736"]
        ports:
            - "9736:9736"
        volumes:
            - dependencies-cache:/data
        networks:
            - dependencies-network


# Networks
networks:
    dependencies-network:
        driver: bridge

# Volumes
volumes:
    dependencies:
    dependencies-cache:
