name: Docker Builds

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                php: [8.0, 8.1, 8.2, 8.3]
                composer-test: [docker-test, docker-test-lowest]

        name: PHP${{ matrix.php }} - ${{ matrix.composer-test }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v1

            -   name: Build Docker Images
                run: composer ${{ matrix.composer-test }}-build ${{ matrix.php }}

            -   name: Pull Docker Images
                run: docker compose pull --ignore-pull-failures

            -   name: Test Docker Images
                run: composer ${{ matrix.composer-test }} ${{ matrix.php }}
