name: Test Suite

on: [push, pull_request]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                php: [8.0, 8.1, 8.2, 8.3]
                dependency-version: [prefer-lowest, prefer-stable]
                composer-script: [test-feature, test-unit]

        name: PHP ${{ matrix.php }} - ${{ matrix.dependency-version }} - ${{ matrix.composer-script }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   name: Install dependencies
                run: |
                    composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

            -   name: Execute tests
                run: composer ${{ matrix.composer-script }}
